sched/sysctl: Remove unused wakeup granularity variables
Since commit 803223b2 ("kernel: sysctl: Remove sched_latency & sched_wakeup_granularity"),
the variables min_wakeup_granularity_ns and max_wakeup_granularity_ns have been unused.

This fixes the following error when CONFIG_SCHED_DEBUG is enabled:
../kernel/sysctl.c:373:12: error: unused variable 'min_wakeup_granularity_ns' [-Werror,-Wunused-variable]
  373 | static int min_wakeup_granularity_ns;                   /* 0 usecs */
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
../kernel/sysctl.c:374:12: error: unused variable 'max_wakeup_granularity_ns' [-Werror,-Wunused-variable]
  374 | static int max_wakeup_granularity_ns = NSEC_PER_SEC;    /* 1 second */
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Ic21d8031e35f6788ca53fcf454e84554f7dccaa9
Signed-off-by: angelomds42 <angelomds42@gmail.com>